version: 2
jobs:
  build:
    working_directory: ~/happinas
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
    steps:
      - checkout

        # Bundlerのバージョン確認
      - run:
          name: Update bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          name: Restore bundle cache
          key: happinas-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4

      - save_cache:
          name: Store bundle cache
          key: happinas-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Update ruby-advisory-db
          command: bundle exec bundler-audit update

      - run:
          name: Patch-level verification for bundler
          command: bundle exec bundler-audit

      - run:
          name: Rubocop style check
          command: bundle exec rubocop --display-cop-names

      - run:
          name: Check application for security vulnerabilities
          command: bundle exec brakeman

      - run:
          name: Code quality report
          command: bundle exec rubycritic --no-browser --minimum-score 100 --path /tmp/rubycritic/rubycritic.html app lib

      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace

      - run:
          name: Run Tests
          command: RAILS_ENV=test bundle exec rspec

      - store_test_results:
           path: /tmp/test-results

      - store_artifacts:
          path: /tmp/rubycritic
